fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-case-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: end-of-file-fixer
        # python, js and ts only
        files: \.(py|js|ts)$
      - id: mixed-line-ending
        files: \.(py|js|ts)$
        args:
          - --fix=lf
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff # Run the linter.
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format # Run the formatter.
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
